spring:
  application:
    name: amp-eureka-server
    #安全检查配置
  security:
    user:
      name: root
      password: root
server:
  port: 8761
eureka:
  instance:
    hostname: serviceCenter
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      #开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
    #此项目不作为客户端注册
    register-with-eureka: false

