server:
  port: 8081
spring:
  application:
    name: apm-order
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@serviceCenter:8761/eureka,http://root:root@serviceCenter2:8761/eureka